rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - jruby-19mode

script: bundle exec rake spec

matrix:
  include:
    - rvm: 1.9.3
      gemfile: gemfiles/gemfile.latest-pedant
  allow_failures:
    - rvm: 1.8.7           # We support 1.8.7, but chef-pedant doesn't
    - rvm: jruby-19mode    # Mixlib Shellout uses fork+exec
    - gemfile: gemfiles/gemfile.latest-pedant
